Experiment 14:

Part A - Data Normalization

Name : Srujan Nalawade

PRN : 25070123140

In [22]:
import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price' : [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_sold' : [25, 65, 35, 80, 50, 15],
    'Discount' : [10, 15, 12, 20, 18, 8]
}

df = pd.DataFrame(data)
df

      Product  Price  Units_sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          65        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [23]:
#1. Min-Max Normalization
#Min-max normalization for price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print('\nMin-Max Normalization for Price')
print(df[['Product','Price', 'Price_MinMax']])

Min-Max Normalization for Price
      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [24]:
# Normalize multiple columns
cols = ['Price', 'Units_sold', 'Discount']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print('\nNormalized dataset: ')
print(df_norm)

Normalized dataset:
      Price  Units_sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.769231  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [25]:
#2. Z-score normalization

df['Units_sold_Zscore'] = (df['Units_sold'] - df['Units_sold'].mean()) / df['Units_sold'].std()

print('\nZ-score normalization for Units_sold')
print(df[['Product','Units_sold', 'Units_sold_Zscore']])

Z-score normalization for Units_sold
      Product  Units_sold  Units_sold_Zscore
0      Laptop          25          -0.809776
1      Mobile          65           0.809776
2      Tablet          35          -0.404888
3  Headphones          80           1.417109
4  Smartwatch          50           0.202444
5      Camera          15          -1.214664

In [26]:
#3. Decimal scaling
df['Price_Decimal'] = df['Price'] / 100000

print('\nDecimal scaling for Price')
print(df[['Product','Price', 'Price_Decimal']])

Decimal scaling for Price
      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

Amazon Dataset Operations:

In [27]:
# Data normalization
import pandas as pd
df = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [28]:
#1. Min-Max normalization

cols = ['Price', 'Units_Sold', 'Reviews']

df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print('\nNormalized dataset: ')
print(df_norm)

Normalized dataset:
       Price  Units_Sold   Reviews
0   0.020243    0.518519  0.291005
1   0.048583    0.277778  0.148148
2   0.016194    0.203704  0.119048
3   0.089069    0.629630  0.444444
4   0.149798    0.833333  0.695767
5   0.036437    0.592593  0.351852
6   0.024291    0.129630  0.052910
7   0.064777    0.351852  0.185185
8   0.210526    0.481481  0.378307
9   0.028340    0.222222  0.089947
10  0.311741    1.000000  1.000000
11  0.174089    0.407407  0.444444
12  0.052632    0.500000  0.232804
13  0.016194    0.092593  0.031746
14  0.024291    0.240741  0.119048
15  0.251012    0.444444  0.497354
16  0.036437    0.259259  0.089947
17  0.068826    0.648148  0.312169
18  0.109312    0.851852  0.814815
19  0.040486    0.351852  0.148148
20  0.008097    0.148148  0.000000
21  0.089069    0.444444  0.272487
22  0.352227    0.185185  0.219577
23  0.020243    0.259259  0.079365
24  0.129555    0.592593  0.444444
25  0.174089    0.166667  0.148148
26  0.514170    0.129630  0.708995
27  0.076923    0.370370  0.232804
28  0.016194    0.314815  0.121693
29  0.048583    0.351852  0.150794
30  0.392713    0.240741  0.444444
31  0.230769    0.203704  0.351852
32  0.129555    0.666667  0.550265
33  0.473684    0.092593  0.272487
34  0.635628    0.037037  0.444444
35  0.012146    0.166667  0.007937
36  0.020243    0.462963  0.126984
37  0.000000    0.574074  0.047619
38  0.028340    0.259259  0.079365
39  0.048583    0.111111  0.026455
40  0.109312    0.148148  0.113757
41  0.433198    0.074074  0.206349
42  0.190283    0.351852  0.444444
43  1.000000    0.000000  0.365079
44  0.068826    0.444444  0.259259
45  0.311741    0.240741  0.470899
46  0.757085    0.092593  0.325397
47  0.089069    0.185185  0.148148
48  0.129555    0.148148  0.119048
49  0.028340    0.314815  0.089947

In [29]:
# Z-score normalization

df['Units_Sold_zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Units_Sold_zscore
0,P101,Wireless Mouse,799,4.3,1520,350,0.812282
1,P102,Bluetooth Speaker,1499,4.5,980,220,-0.260855
2,P103,USB Keyboard,699,4.1,870,180,-0.591051
3,P104,Gaming Headset,2499,4.6,2100,410,1.307576
4,P105,Smartwatch,3999,4.4,3050,520,2.215615
5,P106,Power Bank,1199,4.2,1750,390,1.142478
6,P107,Laptop Stand,899,4.0,620,140,-0.921247
7,P108,Webcam,1899,4.3,1120,260,0.069341
8,P109,Portable SSD,5499,4.7,1850,330,0.647184
9,P110,Wireless Charger,999,4.2,760,190,-0.508502
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,2.958556
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.316988
12,P113,Gaming Mouse,1599,4.4,1300,340,0.729733
13,P114,Tablet Stand,699,4.1,540,120,-1.086345
14,P115,USB Hub,899,4.2,870,200,-0.425953
15,P116,External Hard Drive,6499,4.6,2300,310,0.482086
16,P117,Smartphone Tripod,1199,4.3,760,210,-0.343404
17,P118,Laptop Backpack,1999,4.4,1600,420,1.390125
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,2.298164
19,P120,LED Desk Lamp,1299,4.3,980,260,0.069341
20,P121,Phone Holder,499,4.0,420,150,-0.838698
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.482086
22,P123,Portable Monitor,8999,4.6,1250,170,-0.673600
23,P124,Smart Plug,799,4.2,720,210,-0.343404
24,P125,WiFi Router,3499,4.5,2100,390,1.142478
25,P126,Graphics Tablet,4599,4.4,980,160,-0.756149
26,P127,VR Headset,12999,4.7,3100,140,-0.921247
27,P128,Microphone,2199,4.3,1300,270,0.151890
28,P129,Smart Light Bulb,699,4.2,880,240,-0.095757
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.069341
30,P131,Action Camera,9999,4.6,2100,200,-0.425953
31,P132,Smart Doorbell,5999,4.5,1750,180,-0.591051
32,P133,Streaming Stick,3499,4.4,2500,430,1.472674
33,P134,Portable Projector,11999,4.6,1450,120,-1.086345
34,P135,Gaming Chair,15999,4.7,2100,90,-1.333992
35,P136,Desk Organizer,599,4.1,450,160,-0.756149
36,P137,USB Flash Drive,799,4.2,900,320,0.564635
37,P138,Phone Screen Protector,299,4.0,600,380,1.059929
38,P139,Laptop Sleeve,999,4.3,720,210,-0.343404
39,P140,Wireless Presenter,1499,4.4,520,130,-1.003796
40,P141,Tablet Keyboard Case,2999,4.5,850,150,-0.838698
41,P142,Smart Thermostat,10999,4.6,1200,110,-1.168894
42,P143,Security Camera,4999,4.4,2100,260,0.069341
43,P144,Drone Camera,24999,4.7,1800,70,-1.499090
44,P145,Electric Kettle,1999,4.3,1400,310,0.482086
45,P146,Air Fryer,7999,4.6,2200,200,-0.425953
46,P147,Robot Vacuum,18999,4.5,1650,120,-1.086345
47,P148,Smart Scale,2499,4.4,980,170,-0.673600
48,P149,Digital Photo Frame,3499,4.3,870,150,-0.838698
49,P150,Portable Fan,999,4.2,760,240,-0.095757

In [30]:
# Decimal Scaling

df['Price_decimal'] = df['Price'] / 100000
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Units_Sold_zscore,Price_decimal
0,P101,Wireless Mouse,799,4.3,1520,350,0.812282,0.00799
1,P102,Bluetooth Speaker,1499,4.5,980,220,-0.260855,0.01499
2,P103,USB Keyboard,699,4.1,870,180,-0.591051,0.00699
3,P104,Gaming Headset,2499,4.6,2100,410,1.307576,0.02499
4,P105,Smartwatch,3999,4.4,3050,520,2.215615,0.03999
5,P106,Power Bank,1199,4.2,1750,390,1.142478,0.01199
6,P107,Laptop Stand,899,4.0,620,140,-0.921247,0.00899
7,P108,Webcam,1899,4.3,1120,260,0.069341,0.01899
8,P109,Portable SSD,5499,4.7,1850,330,0.647184,0.05499
9,P110,Wireless Charger,999,4.2,760,190,-0.508502,0.00999
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,2.958556,0.07999
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.316988,0.04599
12,P113,Gaming Mouse,1599,4.4,1300,340,0.729733,0.01599
13,P114,Tablet Stand,699,4.1,540,120,-1.086345,0.00699
14,P115,USB Hub,899,4.2,870,200,-0.425953,0.00899
15,P116,External Hard Drive,6499,4.6,2300,310,0.482086,0.06499
16,P117,Smartphone Tripod,1199,4.3,760,210,-0.343404,0.01199
17,P118,Laptop Backpack,1999,4.4,1600,420,1.390125,0.01999
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,2.298164,0.02999
19,P120,LED Desk Lamp,1299,4.3,980,260,0.069341,0.01299
20,P121,Phone Holder,499,4.0,420,150,-0.838698,0.00499
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.482086,0.02499
22,P123,Portable Monitor,8999,4.6,1250,170,-0.673600,0.08999
23,P124,Smart Plug,799,4.2,720,210,-0.343404,0.00799
24,P125,WiFi Router,3499,4.5,2100,390,1.142478,0.03499
25,P126,Graphics Tablet,4599,4.4,980,160,-0.756149,0.04599
26,P127,VR Headset,12999,4.7,3100,140,-0.921247,0.12999
27,P128,Microphone,2199,4.3,1300,270,0.151890,0.02199
28,P129,Smart Light Bulb,699,4.2,880,240,-0.095757,0.00699
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.069341,0.01499
30,P131,Action Camera,9999,4.6,2100,200,-0.425953,0.09999
31,P132,Smart Doorbell,5999,4.5,1750,180,-0.591051,0.05999
32,P133,Streaming Stick,3499,4.4,2500,430,1.472674,0.03499
33,P134,Portable Projector,11999,4.6,1450,120,-1.086345,0.11999
34,P135,Gaming Chair,15999,4.7,2100,90,-1.333992,0.15999
35,P136,Desk Organizer,599,4.1,450,160,-0.756149,0.00599
36,P137,USB Flash Drive,799,4.2,900,320,0.564635,0.00799
37,P138,Phone Screen Protector,299,4.0,600,380,1.059929,0.00299
38,P139,Laptop Sleeve,999,4.3,720,210,-0.343404,0.00999
39,P140,Wireless Presenter,1499,4.4,520,130,-1.003796,0.01499
40,P141,Tablet Keyboard Case,2999,4.5,850,150,-0.838698,0.02999
41,P142,Smart Thermostat,10999,4.6,1200,110,-1.168894,0.10999
42,P143,Security Camera,4999,4.4,2100,260,0.069341,0.04999
43,P144,Drone Camera,24999,4.7,1800,70,-1.499090,0.24999
44,P145,Electric Kettle,1999,4.3,1400,310,0.482086,0.01999
45,P146,Air Fryer,7999,4.6,2200,200,-0.425953,0.07999
46,P147,Robot Vacuum,18999,4.5,1650,120,-1.086345,0.18999
47,P148,Smart Scale,2499,4.4,980,170,-0.673600,0.02499
48,P149,Digital Photo Frame,3499,4.3,870,150,-0.838698,0.03499
49,P150,Portable Fan,999,4.2,760,240,-0.095757,0.00999

In [31]:
# Turning categorical variables into quantitative variables

data = {
    'Order_ID' : [1001, 1002, 1003, 1004, 1005, 1006],
    'Customer_Gender' : ['Male', 'Female', 'Male', 'Female', 'Male', 'Male'],
    'Product_Category' : ['Electronics', 'Clothing', 'Home', 'Electronics', 'Beauty', 'Electronics'],
    'Payment_Method' : ['Credit Card', 'UPI', 'UPI', 'Credit Card', 'UPI', 'Credit Card'],
    'City' : ['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Hyderabad'],
    'Order_value' : [4500, 2300, 3200, 5200, 1800, 4100]
}

df = pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Product_Category,Payment_Method,City,Order_value
0,1001,Male,Electronics,Credit Card,Pune,4500
1,1002,Female,Clothing,UPI,Mumbai,2300
2,1003,Male,Home,UPI,Delhi,3200
3,1004,Female,Electronics,Credit Card,Bangalore,5200
4,1005,Male,Beauty,UPI,Pune,1800
5,1006,Male,Electronics,Credit Card,Hyderabad,4100

In [32]:
# Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,Product_Category,Payment_Method,City,Order_value,Gender_Label
0,1001,Male,Electronics,Credit Card,Pune,4500,1
1,1002,Female,Clothing,UPI,Mumbai,2300,0
2,1003,Male,Home,UPI,Delhi,3200,1
3,1004,Female,Electronics,Credit Card,Bangalore,5200,0
4,1005,Male,Beauty,UPI,Pune,1800,1
5,1006,Male,Electronics,Credit Card,Hyderabad,4100,1

In [33]:
# Method 2: One Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Product_Category'])
df_encoded

,Order_ID,Customer_Gender,Payment_Method,City,Order_value,Gender_Label,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home
0,1001,Male,Credit Card,Pune,4500,1,False,False,True,False
1,1002,Female,UPI,Mumbai,2300,0,False,True,False,False
2,1003,Male,UPI,Delhi,3200,1,False,False,False,True
3,1004,Female,Credit Card,Bangalore,5200,0,False,False,True,False
4,1005,Male,UPI,Pune,1800,1,True,False,False,False
5,1006,Male,Credit Card,Hyderabad,4100,1,False,False,True,False

In [34]:
#Encoding Multiple Columns
df_multi = pd.get_dummies(df, columns=['Customer_Gender', 'City'])
df_multi

,Order_ID,Product_Category,Payment_Method,Order_value,Gender_Label,Customer_Gender_Female,Customer_Gender_Male,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,1001,Electronics,Credit Card,4500,1,False,True,False,False,False,False,True
1,1002,Clothing,UPI,2300,0,True,False,False,False,False,True,False
2,1003,Home,UPI,3200,1,False,True,False,True,False,False,False
3,1004,Electronics,Credit Card,5200,0,True,False,True,False,False,False,False
4,1005,Beauty,UPI,1800,1,False,True,False,False,False,False,True
5,1006,Electronics,Credit Card,4100,1,False,True,False,False,True,False,False

In [35]:
# Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)
df_dummy

,Order_ID,Customer_Gender,Product_Category,City,Order_value,Gender_Label,Payment_Method_UPI
0,1001,Male,Electronics,Pune,4500,1,False
1,1002,Female,Clothing,Mumbai,2300,0,True
2,1003,Male,Home,Delhi,3200,1,True
3,1004,Female,Electronics,Bangalore,5200,0,False
4,1005,Male,Beauty,Pune,1800,1,True
5,1006,Male,Electronics,Hyderabad,4100,1,False

Student Dataset Operations:

In [36]:
df = pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [37]:
# Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Gender_Label'] = le.fit_transform(df['Gender'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,0
1,102,Male,IT,7.5,1,85,Not Placed,0,1
2,103,Female,ENTC,9.1,0,96,Placed,550000,0
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1
4,105,Female,Computer,8.7,0,88,Placed,480000,0
5,106,Male,Civil,7.2,3,72,Not Placed,0,1
6,107,Female,IT,8.9,0,91,Placed,500000,0
7,108,Male,Computer,6.5,1,80,Not Placed,0,1
8,109,Female,ENTC,7.8,0,84,Placed,420000,0
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1

In [38]:
# Method 2: One Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Attendance_Percentage'])
df_encoded

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Placement_Status,Salary,Gender_Label,Attendance_Percentage_72,Attendance_Percentage_76,Attendance_Percentage_78,Attendance_Percentage_80,Attendance_Percentage_84,Attendance_Percentage_85,Attendance_Percentage_88,Attendance_Percentage_91,Attendance_Percentage_92,Attendance_Percentage_96
0,101,Female,Computer,8.2,0,Placed,450000,0,False,False,False,False,False,False,False,False,True,False
1,102,Male,IT,7.5,1,Not Placed,0,1,False,False,False,False,False,True,False,False,False,False
2,103,Female,ENTC,9.1,0,Placed,550000,0,False,False,False,False,False,False,False,False,False,True
3,104,Male,Mechanical,6.8,2,Not Placed,0,1,False,False,True,False,False,False,False,False,False,False
4,105,Female,Computer,8.7,0,Placed,480000,0,False,False,False,False,False,False,True,False,False,False
5,106,Male,Civil,7.2,3,Not Placed,0,1,True,False,False,False,False,False,False,False,False,False
6,107,Female,IT,8.9,0,Placed,500000,0,False,False,False,False,False,False,False,True,False,False
7,108,Male,Computer,6.5,1,Not Placed,0,1,False,False,False,True,False,False,False,False,False,False
8,109,Female,ENTC,7.8,0,Placed,420000,0,False,False,False,False,True,False,False,False,False,False
9,110,Male,Mechanical,7.0,2,Not Placed,0,1,False,True,False,False,False,False,False,False,False,False

In [39]:
# Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df, columns=['Salary'], drop_first=True)
df_dummy

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Gender_Label,Salary_420000,Salary_450000,Salary_480000,Salary_500000,Salary_550000
0,101,Female,Computer,8.2,0,92,Placed,0,False,True,False,False,False
1,102,Male,IT,7.5,1,85,Not Placed,1,False,False,False,False,False
2,103,Female,ENTC,9.1,0,96,Placed,0,False,False,False,False,True
3,104,Male,Mechanical,6.8,2,78,Not Placed,1,False,False,False,False,False
4,105,Female,Computer,8.7,0,88,Placed,0,False,False,True,False,False
5,106,Male,Civil,7.2,3,72,Not Placed,1,False,False,False,False,False
6,107,Female,IT,8.9,0,91,Placed,0,False,False,False,True,False
7,108,Male,Computer,6.5,1,80,Not Placed,1,False,False,False,False,False
8,109,Female,ENTC,7.8,0,84,Placed,0,True,False,False,False,False
9,110,Male,Mechanical,7.0,2,76,Not Placed,1,False,False,False,False,False